// Code generated by scripts/generate_script_cleaner.go; DO NOT EDIT.
package main

import "strings"

func cleanScriptContent(script string) string {
    lines := strings.Split(script, "\n")
    lines = trimEdges(lines)
    if len(lines) == 0 {
        return ""
    }

    if first := strings.TrimSpace(lines[0]); strings.HasPrefix(first, "<") || strings.HasPrefix(first, ">") {
        lines = lines[1:]
    }

    lines = trimEdges(lines)
    if len(lines) == 0 {
        return ""
    }

    if strings.TrimSpace(lines[len(lines)-1]) == "}" {
        lines = lines[:len(lines)-1]
    }

    lines = trimEdges(lines)
    if len(lines) == 0 {
        return ""
    }

    return strings.Join(lines, "\n")
}

func trimEdges(lines []string) []string {
    for len(lines) > 0 && strings.TrimSpace(lines[0]) == "" {
        lines = lines[1:]
    }
    for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
        lines = lines[:len(lines)-1]
    }
    return lines
}
