// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {importers} from '../models';

export function AddEnvVariable(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdates():Promise<app.UpdateInfo>;

export function ClearPreparedUpdate():Promise<void>;

export function ClearScriptLogs():Promise<void>;

export function DeleteSecret(arg1:string,arg2:string):Promise<Record<string, Array<string>>>;

export function EnsureServiceRunning(arg1:string):Promise<void>;

export function ExportSecrets():Promise<Record<string, Record<string, string>>>;

export function GetAppVersion():Promise<string>;

export function GetEnvVariables(arg1:string):Promise<Record<string, string>>;

export function GetEnvironments():Promise<Record<string, Record<string, string>>>;

export function GetExamplesFile():Promise<app.ExamplesForFirstRunResponse>;

export function GetExamplesForFirstRun():Promise<app.ExamplesForFirstRunResponse>;

export function GetScriptLogs():Promise<Array<app.ScriptLogEntry>>;

export function GetSecretValue(arg1:string,arg2:string):Promise<string>;

export function GetVariable(arg1:string):Promise<string>;

export function GetVariables():Promise<Record<string, string>>;

export function GetVaultInfo():Promise<app.VaultInfo>;

export function HasMasterPassword():Promise<boolean>;

export function ImportCollection(arg1:string):Promise<importers.ImportResult>;

export function ImportFromPath(arg1:string):Promise<importers.ImportResult>;

export function IsFirstRun():Promise<boolean>;

export function ListReleases():Promise<Array<app.ReleaseInfo>>;

export function ListSecrets():Promise<Record<string, Array<string>>>;

export function LoadFileHistory(arg1:string):Promise<string>;

export function LoadFileHistoryFromDir(arg1:string,arg2:string):Promise<string>;

export function LoadFileHistoryFromHttpFile(arg1:string):Promise<string>;

export function LoadFileHistoryFromRunLocation(arg1:string):Promise<string>;

export function LoadWindowState():Promise<app.WindowState>;

export function MarkFirstRunComplete():Promise<void>;

export function MigrateResponsesFromRunLocationToHttpFile(arg1:string,arg2:string):Promise<string>;

export function OpenFileDialog():Promise<Array<string>>;

export function OpenImportDirectoryDialog():Promise<string>;

export function OpenImportFileDialog():Promise<string>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function ParseResponseForVariables(arg1:string):Promise<void>;

export function ReadFileContents(arg1:string):Promise<string>;

export function RecordScriptLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameEnvironment(arg1:string,arg2:string):Promise<void>;

export function ResetVault():Promise<Record<string, Array<string>>>;

export function RestoreWindowState():Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SaveBase64ToFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveBinaryResponse(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveBinaryResponseToPath(arg1:string,arg2:string):Promise<void>;

export function SaveFileContents(arg1:string,arg2:string):Promise<string>;

export function SaveResponseFile(arg1:string,arg2:string):Promise<string>;

export function SaveResponseFileToRunLocation(arg1:string,arg2:string):Promise<string>;

export function SaveSecret(arg1:string,arg2:string,arg3:string):Promise<Record<string, Array<string>>>;

export function SaveWindowState():Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SetEnvVariable(arg1:string,arg2:string):Promise<void>;

export function SetEnvironment(arg1:string):Promise<void>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function SetVariable(arg1:string,arg2:string):Promise<void>;

export function ShowSaveDialog(arg1:string):Promise<string>;

export function StartUpdateAndRestart(arg1:string):Promise<void>;

export function VerifyMasterPassword(arg1:string):Promise<boolean>;
