// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEnvVariable(arg1, arg2) {
  return window['go']['app']['App']['AddEnvVariable'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function ClearPreparedUpdate() {
  return window['go']['app']['App']['ClearPreparedUpdate']();
}

export function ClearScriptLogs() {
  return window['go']['app']['App']['ClearScriptLogs']();
}

export function DeleteSecret(arg1, arg2) {
  return window['go']['app']['App']['DeleteSecret'](arg1, arg2);
}

export function EnsureServiceRunning(arg1) {
  return window['go']['app']['App']['EnsureServiceRunning'](arg1);
}

export function ExportSecrets() {
  return window['go']['app']['App']['ExportSecrets']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetEnvVariables(arg1) {
  return window['go']['app']['App']['GetEnvVariables'](arg1);
}

export function GetEnvironments() {
  return window['go']['app']['App']['GetEnvironments']();
}

export function GetExamplesFile() {
  return window['go']['app']['App']['GetExamplesFile']();
}

export function GetExamplesForFirstRun() {
  return window['go']['app']['App']['GetExamplesForFirstRun']();
}

export function GetScriptLogs() {
  return window['go']['app']['App']['GetScriptLogs']();
}

export function GetSecretValue(arg1, arg2) {
  return window['go']['app']['App']['GetSecretValue'](arg1, arg2);
}

export function GetVariable(arg1) {
  return window['go']['app']['App']['GetVariable'](arg1);
}

export function GetVariables() {
  return window['go']['app']['App']['GetVariables']();
}

export function GetVaultInfo() {
  return window['go']['app']['App']['GetVaultInfo']();
}

export function HasMasterPassword() {
  return window['go']['app']['App']['HasMasterPassword']();
}

export function ImportCollection(arg1) {
  return window['go']['app']['App']['ImportCollection'](arg1);
}

export function ImportFromPath(arg1) {
  return window['go']['app']['App']['ImportFromPath'](arg1);
}

export function IsFirstRun() {
  return window['go']['app']['App']['IsFirstRun']();
}

export function ListReleases() {
  return window['go']['app']['App']['ListReleases']();
}

export function ListSecrets() {
  return window['go']['app']['App']['ListSecrets']();
}

export function LoadFileHistory(arg1) {
  return window['go']['app']['App']['LoadFileHistory'](arg1);
}

export function LoadFileHistoryFromDir(arg1, arg2) {
  return window['go']['app']['App']['LoadFileHistoryFromDir'](arg1, arg2);
}

export function LoadFileHistoryFromHttpFile(arg1) {
  return window['go']['app']['App']['LoadFileHistoryFromHttpFile'](arg1);
}

export function LoadFileHistoryFromRunLocation(arg1) {
  return window['go']['app']['App']['LoadFileHistoryFromRunLocation'](arg1);
}

export function LoadWindowState() {
  return window['go']['app']['App']['LoadWindowState']();
}

export function MarkFirstRunComplete() {
  return window['go']['app']['App']['MarkFirstRunComplete']();
}

export function MigrateResponsesFromRunLocationToHttpFile(arg1, arg2) {
  return window['go']['app']['App']['MigrateResponsesFromRunLocationToHttpFile'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['app']['App']['OpenFileDialog']();
}

export function OpenImportDirectoryDialog() {
  return window['go']['app']['App']['OpenImportDirectoryDialog']();
}

export function OpenImportFileDialog() {
  return window['go']['app']['App']['OpenImportFileDialog']();
}

export function OpenReleaseURL(arg1) {
  return window['go']['app']['App']['OpenReleaseURL'](arg1);
}

export function ParseResponseForVariables(arg1) {
  return window['go']['app']['App']['ParseResponseForVariables'](arg1);
}

export function ReadFileContents(arg1) {
  return window['go']['app']['App']['ReadFileContents'](arg1);
}

export function RecordScriptLog(arg1, arg2, arg3) {
  return window['go']['app']['App']['RecordScriptLog'](arg1, arg2, arg3);
}

export function RenameEnvironment(arg1, arg2) {
  return window['go']['app']['App']['RenameEnvironment'](arg1, arg2);
}

export function ResetVault() {
  return window['go']['app']['App']['ResetVault']();
}

export function RestoreWindowState() {
  return window['go']['app']['App']['RestoreWindowState']();
}

export function RevealInFinder(arg1) {
  return window['go']['app']['App']['RevealInFinder'](arg1);
}

export function SaveFileContents(arg1, arg2) {
  return window['go']['app']['App']['SaveFileContents'](arg1, arg2);
}

export function SaveBase64ToFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveBase64ToFile'](arg1, arg2, arg3);
}

export function SaveBinaryResponse(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveBinaryResponse'](arg1, arg2, arg3);
}

export function SaveBinaryResponseToPath(arg1, arg2) {
  return window['go']['app']['App']['SaveBinaryResponseToPath'](arg1, arg2);
}

export function SaveResponseFile(arg1, arg2) {
  return window['go']['app']['App']['SaveResponseFile'](arg1, arg2);
}

export function SaveResponseFileToRunLocation(arg1, arg2) {
  return window['go']['app']['App']['SaveResponseFileToRunLocation'](arg1, arg2);
}

export function SaveSecret(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveSecret'](arg1, arg2, arg3);
}

export function SaveWindowState() {
  return window['go']['app']['App']['SaveWindowState']();
}

export function SendNotification(arg1, arg2) {
  return window['go']['app']['App']['SendNotification'](arg1, arg2);
}

export function SetEnvVariable(arg1, arg2) {
  return window['go']['app']['App']['SetEnvVariable'](arg1, arg2);
}

export function SetEnvironment(arg1) {
  return window['go']['app']['App']['SetEnvironment'](arg1);
}

export function SetMasterPassword(arg1) {
  return window['go']['app']['App']['SetMasterPassword'](arg1);
}

export function SetVariable(arg1, arg2) {
  return window['go']['app']['App']['SetVariable'](arg1, arg2);
}

export function ShowSaveDialog(arg1) {
  return window['go']['app']['App']['ShowSaveDialog'](arg1);
}

export function StartUpdateAndRestart(arg1) {
  return window['go']['app']['App']['StartUpdateAndRestart'](arg1);
}

export function VerifyMasterPassword(arg1) {
  return window['go']['app']['App']['VerifyMasterPassword'](arg1);
}
