package main

import (
	"fmt"
	"os"
	"path/filepath"
)

const goTemplate = `// Code generated by scripts/generate_script_cleaner.go; DO NOT EDIT.
package main

import "strings"

func cleanScriptContent(script string) string {
    lines := strings.Split(script, "\n")
    lines = trimEdges(lines)
    if len(lines) == 0 {
        return ""
    }

    if first := strings.TrimSpace(lines[0]); strings.HasPrefix(first, "<") || strings.HasPrefix(first, ">") {
        lines = lines[1:]
    }

    lines = trimEdges(lines)
    if len(lines) == 0 {
        return ""
    }

    if strings.TrimSpace(lines[len(lines)-1]) == "}" {
        lines = lines[:len(lines)-1]
    }

    lines = trimEdges(lines)
    if len(lines) == 0 {
        return ""
    }

    return strings.Join(lines, "\n")
}

func trimEdges(lines []string) []string {
    for len(lines) > 0 && strings.TrimSpace(lines[0]) == "" {
        lines = lines[1:]
    }
    for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
        lines = lines[:len(lines)-1]
    }
    return lines
}
`

const tsTemplate = `// Code generated by scripts/generate_script_cleaner.go; DO NOT EDIT.
export function cleanScriptContent(script: string): string {
  const lines = script.split('\n');

  trimEdges(lines);
  if (!lines.length) {
    return '';
  }

  const first = lines[0].trim();
  if (first.startsWith('<') || first.startsWith('>')) {
    lines.shift();
  }

  trimEdges(lines);
  if (!lines.length) {
    return '';
  }

  const last = lines[lines.length - 1].trim();
  if (last === '}') {
    lines.pop();
  }

  trimEdges(lines);
  if (!lines.length) {
    return '';
  }

  return lines.join('\n');
}

function trimEdges(lines: string[]): void {
  while (lines.length && lines[0].trim() === '') {
    lines.shift();
  }

  while (lines.length && lines[lines.length - 1].trim() === '') {
    lines.pop();
  }
}
`

func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}

func main() {
	if err := writeFile("script_cleaner_generated.go", []byte(goTemplate)); err != nil {
		panic(fmt.Errorf("writing go cleaner: %w", err))
	}

	if err := writeFile(filepath.Join("frontend", "src", "app", "utils", "script-cleaner.generated.ts"), []byte(tsTemplate)); err != nil {
		panic(fmt.Errorf("writing ts cleaner: %w", err))
	}
}
