// Code generated by scripts/generate_script_cleaner.go; DO NOT EDIT.
export function cleanScriptContent(script: string): string {
  const lines = script.split('\n');

  trimEdges(lines);
  if (!lines.length) {
    return '';
  }

  const first = lines[0].trim();
  if (first.startsWith('<') || first.startsWith('>')) {
    lines.shift();
  }

  trimEdges(lines);
  if (!lines.length) {
    return '';
  }

  const last = lines[lines.length - 1].trim();
  if (last === '}') {
    lines.pop();
  }

  trimEdges(lines);
  if (!lines.length) {
    return '';
  }

  return lines.join('\n');
}

function trimEdges(lines: string[]): void {
  while (lines.length && lines[0].trim() === '') {
    lines.shift();
  }

  while (lines.length && lines[lines.length - 1].trim() === '') {
    lines.pop();
  }
}
