// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEnvVariable(arg1, arg2) {
  return window['go']['main']['App']['AddEnvVariable'](arg1, arg2);
}

export function CancelRequest(arg1) {
  return window['go']['main']['App']['CancelRequest'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearPreparedUpdate() {
  return window['go']['main']['App']['ClearPreparedUpdate']();
}

export function ClearScriptLogs() {
  return window['go']['main']['App']['ClearScriptLogs']();
}

export function DeleteSecret(arg1, arg2) {
  return window['go']['main']['App']['DeleteSecret'](arg1, arg2);
}

export function ExecuteRequests(arg1) {
  return window['go']['main']['App']['ExecuteRequests'](arg1);
}

export function ExecuteRequestsWithID(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRequestsWithID'](arg1, arg2);
}

export function ExportSecrets() {
  return window['go']['main']['App']['ExportSecrets']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetEnvVariables(arg1) {
  return window['go']['main']['App']['GetEnvVariables'](arg1);
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetExamplesFile() {
  return window['go']['main']['App']['GetExamplesFile']();
}

export function GetExamplesForFirstRun() {
  return window['go']['main']['App']['GetExamplesForFirstRun']();
}

export function GetScriptLogs() {
  return window['go']['main']['App']['GetScriptLogs']();
}

export function GetSecretValue(arg1, arg2) {
  return window['go']['main']['App']['GetSecretValue'](arg1, arg2);
}

export function GetVariable(arg1) {
  return window['go']['main']['App']['GetVariable'](arg1);
}

export function GetVariables() {
  return window['go']['main']['App']['GetVariables']();
}

export function GetVaultInfo() {
  return window['go']['main']['App']['GetVaultInfo']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function ListSecrets() {
  return window['go']['main']['App']['ListSecrets']();
}

export function LoadFileHistory(arg1) {
  return window['go']['main']['App']['LoadFileHistory'](arg1);
}

export function LoadFileHistoryFromDir(arg1, arg2) {
  return window['go']['main']['App']['LoadFileHistoryFromDir'](arg1, arg2);
}

export function LoadFileHistoryFromHttpFile(arg1) {
  return window['go']['main']['App']['LoadFileHistoryFromHttpFile'](arg1);
}

export function LoadFileHistoryFromRunLocation(arg1) {
  return window['go']['main']['App']['LoadFileHistoryFromRunLocation'](arg1);
}

export function LoadWindowState() {
  return window['go']['main']['App']['LoadWindowState']();
}

export function MarkFirstRunComplete() {
  return window['go']['main']['App']['MarkFirstRunComplete']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenReleaseURL(arg1) {
  return window['go']['main']['App']['OpenReleaseURL'](arg1);
}

export function ParseHttp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ParseHttp'](arg1, arg2, arg3);
}

export function ParseResponseForVariables(arg1) {
  return window['go']['main']['App']['ParseResponseForVariables'](arg1);
}

export function ReadFileContents(arg1) {
  return window['go']['main']['App']['ReadFileContents'](arg1);
}

export function RecordScriptLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordScriptLog'](arg1, arg2, arg3);
}

export function RenameEnvironment(arg1, arg2) {
  return window['go']['main']['App']['RenameEnvironment'](arg1, arg2);
}

export function ResetVault() {
  return window['go']['main']['App']['ResetVault']();
}

export function RestoreWindowState() {
  return window['go']['main']['App']['RestoreWindowState']();
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveFileContents(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContents'](arg1, arg2);
}

export function SaveResponseFile(arg1, arg2) {
  return window['go']['main']['App']['SaveResponseFile'](arg1, arg2);
}

export function SaveResponseFileToRunLocation(arg1, arg2) {
  return window['go']['main']['App']['SaveResponseFileToRunLocation'](arg1, arg2);
}

export function SaveSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSecret'](arg1, arg2, arg3);
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SendRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3, arg4);
}

export function SendRequestWithID(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendRequestWithID'](arg1, arg2, arg3, arg4, arg5);
}

export function SendRequestWithTimeout(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SendRequestWithTimeout'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetEnvVariable(arg1, arg2) {
  return window['go']['main']['App']['SetEnvVariable'](arg1, arg2);
}

export function SetEnvironment(arg1) {
  return window['go']['main']['App']['SetEnvironment'](arg1);
}

export function SetVariable(arg1, arg2) {
  return window['go']['main']['App']['SetVariable'](arg1, arg2);
}

export function ShowSaveDialog(arg1) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1);
}

export function StartLoadTest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartLoadTest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartUpdateAndRestart(arg1) {
  return window['go']['main']['App']['StartUpdateAndRestart'](arg1);
}
