// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddEnvVariable(arg1:string,arg2:string):Promise<void>;

export function CancelRequest(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClearScriptLogs():Promise<void>;

export function DeleteSecret(arg1:string,arg2:string):Promise<Record<string, Array<string>>>;

export function ExecuteRequests(arg1:Array<Record<string, any>>):Promise<string>;

export function ExecuteRequestsWithID(arg1:string,arg2:Array<Record<string, any>>):Promise<string>;

export function ExportSecrets():Promise<Record<string, Record<string, string>>>;

export function GetAppVersion():Promise<string>;

export function GetEnvVariables(arg1:string):Promise<Record<string, string>>;

export function GetEnvironments():Promise<Record<string, Record<string, string>>>;

export function GetScriptLogs():Promise<Array<main.ScriptLogEntry>>;

export function GetSecretValue(arg1:string,arg2:string):Promise<string>;

export function GetVariable(arg1:string):Promise<string>;

export function GetVariables():Promise<Record<string, string>>;

export function GetVaultInfo():Promise<main.VaultInfo>;

export function ListSecrets():Promise<Record<string, Array<string>>>;

export function LoadFileHistory(arg1:string):Promise<string>;

export function LoadWindowState():Promise<main.WindowState>;

export function OpenFileDialog():Promise<Array<string>>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function ParseHttp(arg1:string,arg2:Record<string, string>,arg3:Record<string, string>):Promise<Array<Record<string, any>>>;

export function ParseResponseForVariables(arg1:string):Promise<void>;

export function ReadFileContents(arg1:string):Promise<string>;

export function RecordScriptLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameEnvironment(arg1:string,arg2:string):Promise<void>;

export function ResetVault():Promise<Record<string, Array<string>>>;

export function RestoreWindowState():Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SaveFileHistory(arg1:string,arg2:string):Promise<void>;

export function SaveSecret(arg1:string,arg2:string,arg3:string):Promise<Record<string, Array<string>>>;

export function SaveWindowState():Promise<void>;

export function SendRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SendRequestWithID(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SendRequestWithTimeout(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function SetEnvVariable(arg1:string,arg2:string):Promise<void>;

export function SetEnvironment(arg1:string):Promise<void>;

export function SetVariable(arg1:string,arg2:string):Promise<void>;
