// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  RequestBlock = 2,
  MethodLine = 3,
  RequestLine = 4,
  AnnotationLine = 5,
  HeaderLine = 6,
  BodyLine = 7,
  BlankLine = 8,
  SeparatorLine = 9
